version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: prplatform_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./crons/envs
    ports:
      - "8000:8000"
    command: /start.sh
    tty: true
    stdin_open: true

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: prplatform_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres
