# Generated by Django 2.0.4 on 2018-04-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180417_1221'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadExercise',
            fields=[
                ('baseexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercises.BaseExercise')),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
            bases=('exercises.baseexercise',),
        ),
        migrations.AddField(
            model_name='baseexercise',
            name='course',
            field=models.ForeignKey(default=1, on_delete='exercises', to='courses.Course'),
            preserve_default=False,
        ),
    ]
