# Generated by Django 2.0.4 on 2018-05-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180426_0754'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralExercise',
            new_name='SubmissionExercise',
        ),
    ]
