# Generated by Django 2.0.4 on 2018-05-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180426_0754'),
        ('exercises', '0002_auto_20180508_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the exercise')),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewexercise_exercises', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submissionexercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercise_exercises', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='reviewexercise',
            name='reviewable_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.SubmissionExercise'),
        ),
    ]
