# Generated by Django 2.0.4 on 2018-04-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20180423_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseexercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.Course'),
        ),
    ]
