# Generated by Django 2.0.4 on 2018-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20180423_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='fileuploadexercise',
            name='upload_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
