# Generated by Django 2.0.4 on 2018-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20180508_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexercise',
            name='text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissionexercise',
            name='file_upload',
            field=models.BooleanField(default=True),
        ),
    ]
