# Generated by Django 2.0.4 on 2018-04-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180425_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExercise',
            fields=[
                ('baseexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercises.BaseExercise')),
                ('file_upload', models.BooleanField()),
                ('upload_instructions', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('exercises.baseexercise',),
        ),
        migrations.RemoveField(
            model_name='fileuploadexercise',
            name='baseexercise_ptr',
        ),
        migrations.DeleteModel(
            name='FileUploadExercise',
        ),
    ]
