# Generated by Django 2.0.4 on 2018-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_reviewexercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='review_count',
            field=models.IntegerField(default=1, verbose_name='How many peer-reviews one student can do'),
        ),
    ]
