# Generated by Django 2.0.4 on 2018-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_reviewexercise_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='model_answer',
            field=models.CharField(blank=True, max_length=6000, verbose_name='Model answer that the student may view in addition to peer-reviewable'),
        ),
    ]
