# Generated by Django 2.0.4 on 2018-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_reviewexercise_model_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexercise',
            name='accepted_file_types',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
