# Generated by Django 2.0.4 on 2018-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_submissionexercise_accepted_file_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionexercise',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='submissionexercise',
            name='text',
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='aplus_course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='aplus_exercise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Student submits a text form'), ('FILE_UPLOAD', 'Student uploads a file'), ('APLUS', 'Submission is done in A+')], default='FILE_UPLOAD', max_length=20),
        ),
    ]
