# Generated by Django 2.0.6 on 2018-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20180629_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
