# Generated by Django 2.0.6 on 2018-09-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_auto_20180906_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='reviewable_exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_exercise', to='exercises.SubmissionExercise'),
        ),
    ]
