# Generated by Django 2.0.6 on 2018-09-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_aplus_apikey'),
        ('exercises', '0015_auto_20180906_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviewexercise',
            options={'ordering': ['-closing_time']},
        ),
        migrations.AlterModelOptions(
            name='submissionexercise',
            options={'ordering': ['-closing_time']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewexercise',
            name='use_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='use_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='use_states',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questioninuse',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ReviewExercise'),
        ),
        migrations.AddField(
            model_name='questioninuse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Question'),
        ),
        migrations.AddField(
            model_name='choiceinuse',
            name='question_in_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, through='exercises.ChoiceInUse', to='exercises.Choice'),
        ),
        migrations.AddField(
            model_name='reviewexercise',
            name='questions',
            field=models.ManyToManyField(through='exercises.QuestionInUse', to='exercises.Question'),
        ),
    ]
