# Generated by Django 2.0.6 on 2018-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20180908_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exercise',
        ),
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ManyToManyField(to='exercises.ReviewExercise'),
        ),
    ]
