# Generated by Django 2.0.6 on 2018-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20180923_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewexercise',
            old_name='review_count',
            new_name='max_reviews_per_student',
        ),
        migrations.AddField(
            model_name='reviewexercise',
            name='max_reviews_per_submission',
            field=models.IntegerField(default=1, verbose_name='How many peer-reviews one submission can receive'),
        ),
    ]
