# Generated by Django 2.0.6 on 2018-09-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_aplus_apikey'),
        ('exercises', '0017_auto_20180908_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.Course'),
            preserve_default=False,
        ),
    ]
