# Generated by Django 2.0.6 on 2018-09-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_auto_20180925_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioninuse',
            options={'ordering': ['value']},
        ),
    ]
