# Generated by Django 2.0.6 on 2018-09-25 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20180925_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=2), null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='reviewexercise',
            name='questions',
        ),
        migrations.AddField(
            model_name='reviewexercise',
            name='questions',
            field=models.ManyToManyField(to='exercises.Question'),
        ),
    ]
