# Generated by Django 2.0.6 on 2018-09-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_aplus_apikey'),
        ('exercises', '0019_auto_20180908_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='courses.Course'),
            preserve_default=False,
        ),
    ]
