# Generated by Django 2.0.6 on 2018-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_auto_20180925_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hide_from_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
