# Generated by Django 2.0.6 on 2018-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_questionchoice_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='use_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionexercise',
            name='use_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.ManyToManyField(related_name='questions', to='exercises.ReviewExercise'),
        ),
    ]
