# Generated by Django 2.0.6 on 2018-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_auto_20180912_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewexercise',
            options={'ordering': ['-closing_time']},
        ),
        migrations.AlterModelOptions(
            name='submissionexercise',
            options={'ordering': ['-closing_time']},
        ),
    ]
