# Generated by Django 2.0.6 on 2018-09-26 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_question_hide_from_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='question_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='PKs of questions'), default=list(), size=None),
            preserve_default=False,
        ),
    ]
