# Generated by Django 2.0.6 on 2018-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_auto_20180913_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexercise',
            name='use_states',
            field=models.BooleanField(default=False),
        ),
    ]
