# Generated by Django 2.0.6 on 2018-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_auto_20180927_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='type',
            field=models.CharField(choices=[('RANDOM', 'Random by other user'), ('CHOOCE', 'Student chooces')], default='RANDOM', max_length=10),
        ),
    ]
