# Generated by Django 2.0.6 on 2018-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_auto_20180927_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='show_reviews_after_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Show peer-reviews only after this date'),
        ),
    ]
