# Generated by Django 2.0.6 on 2018-10-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_reviewexercise_show_reviews_after_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionexercise',
            name='max_submission_count',
            field=models.IntegerField(default=1),
        ),
    ]
