# Generated by Django 2.0.6 on 2018-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_submissionexercise_max_submission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='require_original_submission',
            field=models.BooleanField(default=True, verbose_name='Student cannot peer-review others if she has not made the original submission'),
        ),
    ]
