# Generated by Django 2.0.6 on 2018-11-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_question_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='can_review_own_submission',
            field=models.BooleanField(default=False, verbose_name='Students can peer-review their own submissions'),
        ),
    ]
