# Generated by Django 2.1.2 on 2018-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0029_reviewexercise_can_review_own_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='type',
            field=models.CharField(choices=[('RANDOM', 'Random by other user'), ('CHOOSE', 'Student chooses')], default='RANDOM', max_length=10),
        ),
    ]
