# Generated by Django 2.1.2 on 2018-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0032_auto_20181111_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_file_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.BooleanField(default=False),
        ),
    ]
