# Generated by Django 2.1.2 on 2018-11-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_auto_20181113_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='accepted_file_types',
            new_name='accepted_filetypes',
        ),
        migrations.RenameField(
            model_name='submissionexercise',
            old_name='accepted_file_types',
            new_name='accepted_filetypes',
        ),
    ]
