# Generated by Django 2.1.2 on 2018-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0034_auto_20181113_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='file_upload',
        ),
        migrations.AlterField(
            model_name='question',
            name='accepted_filetypes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
