# Generated by Django 2.1.2 on 2018-11-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20181015_0725'),
        ('exercises', '0035_auto_20181113_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionExerciseDeadlineExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('new_deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeadlineextension_deadline_extensions', to='courses.Course')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='exercises.SubmissionExercise')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeadlineextension_deadline_extensions', to='users.StudentGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeadlineextension_deadline_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
