# Generated by Django 2.1.2 on 2018-11-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0036_submissionexercisedeadlineextension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewexercise',
            old_name='max_reviews_per_student',
            new_name='max_submission_count',
        ),
        migrations.RenameField(
            model_name='reviewexercise',
            old_name='minimum_reviews_per_student',
            new_name='min_submission_count',
        ),
    ]
