# Generated by Django 2.1.2 on 2018-11-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181015_0725'),
        ('courses', '0017_course_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0037_auto_20181116_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionExerciseDeviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('new_deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeviation_deviations', to='courses.Course')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='exercises.SubmissionExercise')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeviation_deviations', to='users.StudentGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissionexercisedeviation_deviations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='submissionexercisedeadlineextension',
            name='course',
        ),
        migrations.RemoveField(
            model_name='submissionexercisedeadlineextension',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='submissionexercisedeadlineextension',
            name='group',
        ),
        migrations.RemoveField(
            model_name='submissionexercisedeadlineextension',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubmissionExerciseDeadlineExtension',
        ),
    ]
