# Generated by Django 2.1.2 on 2018-11-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_auto_20181116_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionexercisedeviation',
            name='course',
        ),
    ]
