# Generated by Django 2.1.2 on 2018-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_reviewexercisedeviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='type',
            field=models.CharField(choices=[('RANDOM', 'Random by other user (prefer oldest with least peer-reviews)'), ('CHOOSE', 'Student chooses'), ('GROUP', 'Students peer-review other students in their own group')], default='RANDOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='submissionexercise',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Student submits a text form'), ('FILE_UPLOAD', 'Student uploads a file'), ('APLUS', 'Submission is done in A+'), ('GROUP_NO_SUBMISSION', "Use this for group peer-reviews (students peer-review each other but don't return any original submissions)")], default='FILE_UPLOAD', max_length=20),
        ),
    ]
