# Generated by Django 2.1.2 on 2018-11-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0042_auto_20181119_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercisedeviation',
            name='extra_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionexercisedeviation',
            name='extra_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
