# Generated by Django 2.1.2 on 2018-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0043_auto_20181119_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='type',
            field=models.CharField(choices=[('RANDOM', 'Random by other user (prefers oldest with least peer-reviews)'), ('CHOOSE', 'Student chooses from a dropdown list of all reviewables'), ('GROUP', 'Students peer-review other students in their own group')], default='RANDOM', max_length=10),
        ),
    ]
