# Generated by Django 2.1.2 on 2018-11-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0044_auto_20181122_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='show_reviews_only_to_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
