# Generated by Django 2.1.4 on 2019-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0047_auto_20181126_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewexercise',
            name='reviewlock_expiry_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='How many hours a reviewlock is valid'),
        ),
    ]
