# Generated by Django 2.1.7 on 2019-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0048_reviewexercise_reviewlock_expiry_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewexercise',
            name='type',
            field=models.CharField(choices=[('RANDOM', 'Random submission by other student (prefers oldest with least peer-reviews)'), ('CHOOSE', 'Student chooses from a dropdown list of all reviewables'), ('GROUP', 'Students peer-review other students in their own group')], default='RANDOM', max_length=10),
        ),
    ]
