# Generated by Django 2.1.7 on 2019-04-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0049_auto_20190303_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewexercise',
            name='model_answer',
        ),
    ]
