# Generated by Django 2.0.4 on 2018-04-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180410_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='url_slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
