# Generated by Django 2.0.4 on 2018-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180411_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Course code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url_slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifier that will be used in URL addressses'),
        ),
    ]
