# Generated by Django 2.0.4 on 2018-04-12 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180411_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='teachers',
            field=models.ManyToManyField(related_name='base_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
