# Generated by Django 2.0.4 on 2018-04-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180417_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basecourse',
            unique_together={('code', 'school')},
        ),
    ]
