# Generated by Django 2.0.4 on 2018-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180508_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('base_course', 'code')},
        ),
    ]
