# Generated by Django 2.0.6 on 2018-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180515_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='aplus_apikey',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
