# Generated by Django 2.1.2 on 2018-12-07 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exercise_order_on_front_page',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
