# Generated by Django 2.1.4 on 2019-01-21 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_exercise_order_on_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecourse',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='base_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
