# Generated by Django 2.1.4 on 2019-01-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplusapicallrequest',
            old_name='aplus_submission_data',
            new_name='hook_data',
        ),
    ]
