# Generated by Django 2.0.4 on 2018-06-05 10:07

from django.db import migrations
import prplatform.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180507_0940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', prplatform.users.models.MyUserManager()),
            ],
        ),
    ]
