# Generated by Django 2.0.6 on 2018-09-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_aplus_apikey'),
        ('users', '0003_auto_20180605_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='courses.Course')),
                ('students', models.ManyToManyField(related_name='my_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
