# Generated by Django 2.2 on 2019-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lti',
            field=models.BooleanField(default=False),
        ),
    ]
