# Generated by Django 2.0.4 on 2018-05-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180511_0850'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalsubmission',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.SubmissionExercise'),
            preserve_default=False,
        ),
    ]
