# Generated by Django 2.0.4 on 2018-05-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180522_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsubmission',
            name='reviewed_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.OriginalSubmission'),
            preserve_default=False,
        ),
    ]
