# Generated by Django 2.0.6 on 2018-09-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentgroup'),
        ('submissions', '0007_reviewlock_review_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalsubmission',
            old_name='submitter',
            new_name='submitter_user',
        ),
        migrations.RenameField(
            model_name='reviewsubmission',
            old_name='submitter',
            new_name='submitter_user',
        ),
        migrations.AddField(
            model_name='originalsubmission',
            name='submitter_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentGroup'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='submitter_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentGroup'),
        ),
    ]
