# Generated by Django 2.0.6 on 2018-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20180913_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalsubmission',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='reviewsubmission',
            options={'ordering': ['-created']},
        ),
    ]
