# Generated by Django 2.0.6 on 2018-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20180913_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalsubmission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('boomerang', 'Boomerang'), ('ready_for_review', 'Ready for review')], default='ready_for_review', max_length=16),
        ),
    ]
