# Generated by Django 2.0.6 on 2018-09-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20180923_1416'),
        ('submissions', '0010_originalsubmission_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='value_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='value_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
