# Generated by Django 2.0.6 on 2018-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_auto_20180925_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value_choice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
