# Generated by Django 2.1.2 on 2018-11-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20181022_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlock',
            name='original_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewlocks', to='submissions.OriginalSubmission'),
        ),
    ]
