# Generated by Django 2.1.2 on 2018-11-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181015_0725'),
        ('submissions', '0016_answer_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlock',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentGroup'),
        ),
    ]
